### ISSUE TITLE
Command line wrapper for this implementation?

### ISSUE THREAD

**Issue by jolespin** [apcamargo/pydustmasker#1]
Looking for an efficient repeat masker command line tool and stumbled across your reimplementation of Dust.  Are there any default parameters you recommend for eukaryotic genome masking (in particular, protists and fungi)? Also, do you plan on developing a CLI wrapper for your implementation to integrate into pipelines easier (eg Pyrodigal)?

**Comment by apcamargo** [comment]
> Are there any default parameters you recommend for eukaryotic genome masking (in particular, protists and fungi)?

I'd just use the defaults for that.

> Also, do you plan on developing a CLI wrapper for your implementation to integrate into pipelines easier (eg Pyrodigal)?

I wanted to, but don't think I'll be able to work on that in the near future. Maturin supports [exposing functions as entrypoints](https://www.maturin.rs/bindings.html?highlight=entrypo#both-binary-and-library), so it should be relatively easy to do even with pure Rust.

**Comment by jolespin** [comment]
Awesome, thanks for the insight!  Looking forward to testing this out in some of my pipelines.  I've been realizing eukaryotic metagenomics requires so many hoops to jump through especially doing it at scale.  Recently just came across [miniprot](https://github.com/lh3/miniprot) but still trying to figure out how to enrich the results since I'm getting wildly different results than [MetaEuk](https://github.com/soedinglab/metaeuk) w/ the same database.
