### ISSUE TITLE
Cargo.lock not included and not ignored

### ISSUE THREAD

**Issue by sanders41** [apcamargo/pydustmasker#3]
When working on #2 I noticed the `Cargo.lock` file gets created and is not included in the commits. Is that on purpose? If yes you could add it to the `.gitignore` so it doesn't accidentally get included. If no it needs to be added still.

**Comment by apcamargo** [comment]
Good catch, I missed that.

I actually meant to ignore the `Cargo.lock` file since this package is meant to be used as a library. I'll add it to `.gitignore`.

**Comment by sanders41** [comment]
If you want to ignore it's fine, but just an FYI `cargo install` installs without the lock while `cargo install --locked` uses it. https://doc.rust-lang.org/cargo/commands/cargo-install.html#dealing-with-the-lockfile

So the lock file would just make sure you are testing with the same versions.

**Comment by apcamargo** [comment]
I didn't know that. Thanks!

I might be missing something obvious, but what is the point with testing the build with a set of dependencies (determined by `Cargo.lock`) that might be different from the dependencies that will be used for the actual build?

What about `maturin`? I saw that `maturin build` and `maturin publish` also provide `--locked` (which, I guess, is just passed to `cargo`), so the default behaviour is to ignore `Carlo.lock`?

**Comment by sanders41** [comment]
For testing it just ensures the same versions are used for consistence. There probably isn't a big chance, but if a tests fails and then it is run again after a dependency updates you no longer know if you are fixing the original issue, or if it is something new from the dependency update.

For maturin using locked for the publish ensures what was tested is what gets released. You are correct that you don't want to pin the Python dependencies for a lib, but the Rust dependencies should be fine to pin because people will be installing a pre-compiled wheel when they install the package and any rust dependencies are specific to that python package. Even if someone was building the wheel themselves, the Rust dependencies and resulting compiled binary would be specific to that Python package. The rust dependencies are not used across multiple packages like the python dependencies.
